//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChange.boomiTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatos", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ActualizarDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PasswordChange.boomiTest.ActualizarDatos.DocenteType DocenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PasswordChange.boomiTest.ActualizarDatos.DocenteType Docente {
            get {
                return this.DocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.DocenteField, value) != true)) {
                    this.DocenteField = value;
                    this.RaisePropertyChanged("Docente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatos.DocenteType", Namespace="")]
        [System.SerializableAttribute()]
        public partial class DocenteType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string Uid_UsuarioField;
            
            private string BarrioField;
            
            private string DireccionField;
            
            private string CelularField;
            
            private string TelefonoField;
            
            private PasswordChange.boomiTest.ActualizarDatos.DocenteType.MunicipioType MunicipioField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Uid_Usuario {
                get {
                    return this.Uid_UsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.Uid_UsuarioField, value) != true)) {
                        this.Uid_UsuarioField = value;
                        this.RaisePropertyChanged("Uid_Usuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
            public string Barrio {
                get {
                    return this.BarrioField;
                }
                set {
                    if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                        this.BarrioField = value;
                        this.RaisePropertyChanged("Barrio");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
            public string Direccion {
                get {
                    return this.DireccionField;
                }
                set {
                    if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                        this.DireccionField = value;
                        this.RaisePropertyChanged("Direccion");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
            public string Celular {
                get {
                    return this.CelularField;
                }
                set {
                    if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                        this.CelularField = value;
                        this.RaisePropertyChanged("Celular");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
            public string Telefono {
                get {
                    return this.TelefonoField;
                }
                set {
                    if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                        this.TelefonoField = value;
                        this.RaisePropertyChanged("Telefono");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
            public PasswordChange.boomiTest.ActualizarDatos.DocenteType.MunicipioType Municipio {
                get {
                    return this.MunicipioField;
                }
                set {
                    if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                        this.MunicipioField = value;
                        this.RaisePropertyChanged("Municipio");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatos.DocenteType.MunicipioType", Namespace="")]
            [System.SerializableAttribute()]
            public partial class MunicipioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                private string IdField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DescripcionField;
                
                private PasswordChange.boomiTest.ActualizarDatos.DocenteType.MunicipioType.DepartamentoType DepartamentoField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string Id {
                    get {
                        return this.IdField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.IdField, value) != true)) {
                            this.IdField = value;
                            this.RaisePropertyChanged("Id");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string Descripcion {
                    get {
                        return this.DescripcionField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                            this.DescripcionField = value;
                            this.RaisePropertyChanged("Descripcion");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
                public PasswordChange.boomiTest.ActualizarDatos.DocenteType.MunicipioType.DepartamentoType Departamento {
                    get {
                        return this.DepartamentoField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                            this.DepartamentoField = value;
                            this.RaisePropertyChanged("Departamento");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
                
                [System.Diagnostics.DebuggerStepThroughAttribute()]
                [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
                [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatos.DocenteType.MunicipioType.DepartamentoType", Namespace="")]
                [System.SerializableAttribute()]
                public partial class DepartamentoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                    
                    [System.NonSerializedAttribute()]
                    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                    
                    private string IdField;
                    
                    [System.Runtime.Serialization.OptionalFieldAttribute()]
                    private string DescripcionField;
                    
                    public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                        get {
                            return this.extensionDataField;
                        }
                        set {
                            this.extensionDataField = value;
                        }
                    }
                    
                    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                    public string Id {
                        get {
                            return this.IdField;
                        }
                        set {
                            if ((object.ReferenceEquals(this.IdField, value) != true)) {
                                this.IdField = value;
                                this.RaisePropertyChanged("Id");
                            }
                        }
                    }
                    
                    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                    public string Descripcion {
                        get {
                            return this.DescripcionField;
                        }
                        set {
                            if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                                this.DescripcionField = value;
                                this.RaisePropertyChanged("Descripcion");
                            }
                        }
                    }
                    
                    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                    
                    protected void RaisePropertyChanged(string propertyName) {
                        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                        if ((propertyChanged != null)) {
                            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                        }
                    }
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatosResponse", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ActualizarDatosResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PasswordChange.boomiTest.ActualizarDatosResponse.ResultadoTransaccionType ResultadoTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PasswordChange.boomiTest.ActualizarDatosResponse.ResultadoTransaccionType ResultadoTransaccion {
            get {
                return this.ResultadoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoTransaccionField, value) != true)) {
                    this.ResultadoTransaccionField = value;
                    this.RaisePropertyChanged("ResultadoTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatosResponse.ResultadoTransaccionType", Namespace="")]
        [System.SerializableAttribute()]
        public partial class ResultadoTransaccionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string CodigoField;
            
            private string MensajeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Codigo {
                get {
                    return this.CodigoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                        this.CodigoField = value;
                        this.RaisePropertyChanged("Codigo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Mensaje {
                get {
                    return this.MensajeField;
                }
                set {
                    if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                        this.MensajeField = value;
                        this.RaisePropertyChanged("Mensaje");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerCertificadoLaboral", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ObtenerCertificadoLaboral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirigidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdColaboradorField, value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((object.ReferenceEquals(this.SalarioField, value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dirigido {
            get {
                return this.DirigidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirigidoField, value) != true)) {
                    this.DirigidoField = value;
                    this.RaisePropertyChanged("Dirigido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Historia {
            get {
                return this.HistoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoriaField, value) != true)) {
                    this.HistoriaField = value;
                    this.RaisePropertyChanged("Historia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerCertificadoLaboralResponse", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ObtenerCertificadoLaboralResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse.ResultadoTransaccionType ResultadoTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse.ResultadoTransaccionType ResultadoTransaccion {
            get {
                return this.ResultadoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoTransaccionField, value) != true)) {
                    this.ResultadoTransaccionField = value;
                    this.RaisePropertyChanged("ResultadoTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerCertificadoLaboralResponse.ResultadoTransaccionType", Namespace="")]
        [System.SerializableAttribute()]
        public partial class ResultadoTransaccionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string CodigoField;
            
            private string MensajeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Codigo {
                get {
                    return this.CodigoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                        this.CodigoField = value;
                        this.RaisePropertyChanged("Codigo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Mensaje {
                get {
                    return this.MensajeField;
                }
                set {
                    if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                        this.MensajeField = value;
                        this.RaisePropertyChanged("Mensaje");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatos", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idColaboradorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string idColaborador {
            get {
                return this.idColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.idColaboradorField, value) != true)) {
                    this.idColaboradorField = value;
                    this.RaisePropertyChanged("idColaborador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatosResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType DocenteField;
        
        private PasswordChange.boomiTest.ObtenerDatosResponse.ResultadoTransaccionType ResultadoTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType Docente {
            get {
                return this.DocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.DocenteField, value) != true)) {
                    this.DocenteField = value;
                    this.RaisePropertyChanged("Docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public PasswordChange.boomiTest.ObtenerDatosResponse.ResultadoTransaccionType ResultadoTransaccion {
            get {
                return this.ResultadoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoTransaccionField, value) != true)) {
                    this.ResultadoTransaccionField = value;
                    this.RaisePropertyChanged("ResultadoTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse.DocenteType", Namespace="")]
        [System.SerializableAttribute()]
        public partial class DocenteType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string Uid_UsuarioField;
            
            private string NombreField;
            
            private string ApellidosField;
            
            private string BarrioField;
            
            private string CedulaField;
            
            private string DireccionField;
            
            private string CelularField;
            
            private string TelefonoField;
            
            private PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.SedeType SedeField;
            
            private PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.MunicipioType MunicipioField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CargoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string EstadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string MailField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Uid_Usuario {
                get {
                    return this.Uid_UsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.Uid_UsuarioField, value) != true)) {
                        this.Uid_UsuarioField = value;
                        this.RaisePropertyChanged("Uid_Usuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
            public string Nombre {
                get {
                    return this.NombreField;
                }
                set {
                    if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                        this.NombreField = value;
                        this.RaisePropertyChanged("Nombre");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
            public string Apellidos {
                get {
                    return this.ApellidosField;
                }
                set {
                    if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                        this.ApellidosField = value;
                        this.RaisePropertyChanged("Apellidos");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
            public string Barrio {
                get {
                    return this.BarrioField;
                }
                set {
                    if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                        this.BarrioField = value;
                        this.RaisePropertyChanged("Barrio");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
            public string Cedula {
                get {
                    return this.CedulaField;
                }
                set {
                    if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                        this.CedulaField = value;
                        this.RaisePropertyChanged("Cedula");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
            public string Direccion {
                get {
                    return this.DireccionField;
                }
                set {
                    if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                        this.DireccionField = value;
                        this.RaisePropertyChanged("Direccion");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
            public string Celular {
                get {
                    return this.CelularField;
                }
                set {
                    if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                        this.CelularField = value;
                        this.RaisePropertyChanged("Celular");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
            public string Telefono {
                get {
                    return this.TelefonoField;
                }
                set {
                    if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                        this.TelefonoField = value;
                        this.RaisePropertyChanged("Telefono");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
            public PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.SedeType Sede {
                get {
                    return this.SedeField;
                }
                set {
                    if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                        this.SedeField = value;
                        this.RaisePropertyChanged("Sede");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
            public PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.MunicipioType Municipio {
                get {
                    return this.MunicipioField;
                }
                set {
                    if ((object.ReferenceEquals(this.MunicipioField, value) != true)) {
                        this.MunicipioField = value;
                        this.RaisePropertyChanged("Municipio");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
            public string Cargo {
                get {
                    return this.CargoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                        this.CargoField = value;
                        this.RaisePropertyChanged("Cargo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
            public string Estado {
                get {
                    return this.EstadoField;
                }
                set {
                    if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                        this.EstadoField = value;
                        this.RaisePropertyChanged("Estado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
            public string Mail {
                get {
                    return this.MailField;
                }
                set {
                    if ((object.ReferenceEquals(this.MailField, value) != true)) {
                        this.MailField = value;
                        this.RaisePropertyChanged("Mail");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse.DocenteType.SedeType", Namespace="")]
            [System.SerializableAttribute()]
            public partial class SedeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                private string IdField;
                
                private string NombreField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string Id {
                    get {
                        return this.IdField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.IdField, value) != true)) {
                            this.IdField = value;
                            this.RaisePropertyChanged("Id");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string Nombre {
                    get {
                        return this.NombreField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                            this.NombreField = value;
                            this.RaisePropertyChanged("Nombre");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
            }
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse.DocenteType.MunicipioType", Namespace="")]
            [System.SerializableAttribute()]
            public partial class MunicipioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                
                [System.NonSerializedAttribute()]
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                private string IdField;
                
                [System.Runtime.Serialization.OptionalFieldAttribute()]
                private string DescripcionField;
                
                private PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.MunicipioType.DepartamentoType DepartamentoField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                    get {
                        return this.extensionDataField;
                    }
                    set {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string Id {
                    get {
                        return this.IdField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.IdField, value) != true)) {
                            this.IdField = value;
                            this.RaisePropertyChanged("Id");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                public string Descripcion {
                    get {
                        return this.DescripcionField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                            this.DescripcionField = value;
                            this.RaisePropertyChanged("Descripcion");
                        }
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
                public PasswordChange.boomiTest.ObtenerDatosResponse.DocenteType.MunicipioType.DepartamentoType Departamento {
                    get {
                        return this.DepartamentoField;
                    }
                    set {
                        if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                            this.DepartamentoField = value;
                            this.RaisePropertyChanged("Departamento");
                        }
                    }
                }
                
                public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                
                protected void RaisePropertyChanged(string propertyName) {
                    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                    if ((propertyChanged != null)) {
                        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                    }
                }
                
                [System.Diagnostics.DebuggerStepThroughAttribute()]
                [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
                [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse.DocenteType.MunicipioType.DepartamentoType", Namespace="")]
                [System.SerializableAttribute()]
                public partial class DepartamentoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
                    
                    [System.NonSerializedAttribute()]
                    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                    
                    private string IdField;
                    
                    [System.Runtime.Serialization.OptionalFieldAttribute()]
                    private string DescripcionField;
                    
                    public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                        get {
                            return this.extensionDataField;
                        }
                        set {
                            this.extensionDataField = value;
                        }
                    }
                    
                    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                    public string Id {
                        get {
                            return this.IdField;
                        }
                        set {
                            if ((object.ReferenceEquals(this.IdField, value) != true)) {
                                this.IdField = value;
                                this.RaisePropertyChanged("Id");
                            }
                        }
                    }
                    
                    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
                    public string Descripcion {
                        get {
                            return this.DescripcionField;
                        }
                        set {
                            if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                                this.DescripcionField = value;
                                this.RaisePropertyChanged("Descripcion");
                            }
                        }
                    }
                    
                    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
                    
                    protected void RaisePropertyChanged(string propertyName) {
                        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                        if ((propertyChanged != null)) {
                            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                        }
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse.ResultadoTransaccionType", Namespace="")]
        [System.SerializableAttribute()]
        public partial class ResultadoTransaccionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string CodigoField;
            
            private string MensajeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Codigo {
                get {
                    return this.CodigoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                        this.CodigoField = value;
                        this.RaisePropertyChanged("Codigo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string Mensaje {
                get {
                    return this.MensajeField;
                }
                set {
                    if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                        this.MensajeField = value;
                        this.RaisePropertyChanged("Mensaje");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.boomi.com/connector/wss", ConfigurationName="boomiTest.WebServiceProviderPortType")]
    public interface WebServiceProviderPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ActualizarDatos del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="ActualizarDatos", ReplyAction="*")]
        PasswordChange.boomiTest.ActualizarDatosResponse1 ActualizarDatos(PasswordChange.boomiTest.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ActualizarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ActualizarDatosResponse1> ActualizarDatosAsync(PasswordChange.boomiTest.ActualizarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerCertificadoLaboral del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerCertificadoLaboral", ReplyAction="*")]
        PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1 ObtenerCertificadoLaboral(PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerCertificadoLaboral", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1> ObtenerCertificadoLaboralAsync(PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerDatos del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerDatos", ReplyAction="*")]
        PasswordChange.boomiTest.ObtenerDatosResponse1 ObtenerDatos(PasswordChange.boomiTest.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerDatosResponse1> ObtenerDatosAsync(PasswordChange.boomiTest.ObtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatos", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ActualizarDatosRequestBody Body;
        
        public ActualizarDatosRequest() {
        }
        
        public ActualizarDatosRequest(PasswordChange.boomiTest.ActualizarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ActualizarDatos ActualizarDatos;
        
        public ActualizarDatosRequestBody() {
        }
        
        public ActualizarDatosRequestBody(PasswordChange.boomiTest.ActualizarDatos ActualizarDatos) {
            this.ActualizarDatos = ActualizarDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatosResponse", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ActualizarDatosResponse1Body Body;
        
        public ActualizarDatosResponse1() {
        }
        
        public ActualizarDatosResponse1(PasswordChange.boomiTest.ActualizarDatosResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarDatosResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ActualizarDatosResponse ActualizarDatosResponse;
        
        public ActualizarDatosResponse1Body() {
        }
        
        public ActualizarDatosResponse1Body(PasswordChange.boomiTest.ActualizarDatosResponse ActualizarDatosResponse) {
            this.ActualizarDatosResponse = ActualizarDatosResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoLaboralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoLaboral", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ObtenerCertificadoLaboralRequestBody Body;
        
        public ObtenerCertificadoLaboralRequest() {
        }
        
        public ObtenerCertificadoLaboralRequest(PasswordChange.boomiTest.ObtenerCertificadoLaboralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoLaboralRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ObtenerCertificadoLaboral ObtenerCertificadoLaboral;
        
        public ObtenerCertificadoLaboralRequestBody() {
        }
        
        public ObtenerCertificadoLaboralRequestBody(PasswordChange.boomiTest.ObtenerCertificadoLaboral ObtenerCertificadoLaboral) {
            this.ObtenerCertificadoLaboral = ObtenerCertificadoLaboral;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoLaboralResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoLaboralResponse", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1Body Body;
        
        public ObtenerCertificadoLaboralResponse1() {
        }
        
        public ObtenerCertificadoLaboralResponse1(PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerCertificadoLaboralResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse ObtenerCertificadoLaboralResponse;
        
        public ObtenerCertificadoLaboralResponse1Body() {
        }
        
        public ObtenerCertificadoLaboralResponse1Body(PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse ObtenerCertificadoLaboralResponse) {
            this.ObtenerCertificadoLaboralResponse = ObtenerCertificadoLaboralResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(PasswordChange.boomiTest.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ObtenerDatos ObtenerDatos;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(PasswordChange.boomiTest.ObtenerDatos ObtenerDatos) {
            this.ObtenerDatos = ObtenerDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://www.boomi.com/connector/wss", Order=0)]
        public PasswordChange.boomiTest.ObtenerDatosResponse1Body Body;
        
        public ObtenerDatosResponse1() {
        }
        
        public ObtenerDatosResponse1(PasswordChange.boomiTest.ObtenerDatosResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtenerDatosResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PasswordChange.boomiTest.ObtenerDatosResponse ObtenerDatosResponse;
        
        public ObtenerDatosResponse1Body() {
        }
        
        public ObtenerDatosResponse1Body(PasswordChange.boomiTest.ObtenerDatosResponse ObtenerDatosResponse) {
            this.ObtenerDatosResponse = ObtenerDatosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProviderPortTypeChannel : PasswordChange.boomiTest.WebServiceProviderPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProviderPortTypeClient : System.ServiceModel.ClientBase<PasswordChange.boomiTest.WebServiceProviderPortType>, PasswordChange.boomiTest.WebServiceProviderPortType {
        
        public WebServiceProviderPortTypeClient() {
        }
        
        public WebServiceProviderPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProviderPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProviderPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProviderPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordChange.boomiTest.ActualizarDatosResponse1 PasswordChange.boomiTest.WebServiceProviderPortType.ActualizarDatos(PasswordChange.boomiTest.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatos(request);
        }
        
        public PasswordChange.boomiTest.ActualizarDatosResponse ActualizarDatos(PasswordChange.boomiTest.ActualizarDatos ActualizarDatos1) {
            PasswordChange.boomiTest.ActualizarDatosRequest inValue = new PasswordChange.boomiTest.ActualizarDatosRequest();
            inValue.Body = new PasswordChange.boomiTest.ActualizarDatosRequestBody();
            inValue.Body.ActualizarDatos = ActualizarDatos1;
            PasswordChange.boomiTest.ActualizarDatosResponse1 retVal = ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ActualizarDatos(inValue);
            return retVal.Body.ActualizarDatosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ActualizarDatosResponse1> PasswordChange.boomiTest.WebServiceProviderPortType.ActualizarDatosAsync(PasswordChange.boomiTest.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordChange.boomiTest.ActualizarDatosResponse1> ActualizarDatosAsync(PasswordChange.boomiTest.ActualizarDatos ActualizarDatos) {
            PasswordChange.boomiTest.ActualizarDatosRequest inValue = new PasswordChange.boomiTest.ActualizarDatosRequest();
            inValue.Body = new PasswordChange.boomiTest.ActualizarDatosRequestBody();
            inValue.Body.ActualizarDatos = ActualizarDatos;
            return ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ActualizarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1 PasswordChange.boomiTest.WebServiceProviderPortType.ObtenerCertificadoLaboral(PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest request) {
            return base.Channel.ObtenerCertificadoLaboral(request);
        }
        
        public PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse ObtenerCertificadoLaboral(PasswordChange.boomiTest.ObtenerCertificadoLaboral ObtenerCertificadoLaboral1) {
            PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest inValue = new PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest();
            inValue.Body = new PasswordChange.boomiTest.ObtenerCertificadoLaboralRequestBody();
            inValue.Body.ObtenerCertificadoLaboral = ObtenerCertificadoLaboral1;
            PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1 retVal = ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ObtenerCertificadoLaboral(inValue);
            return retVal.Body.ObtenerCertificadoLaboralResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1> PasswordChange.boomiTest.WebServiceProviderPortType.ObtenerCertificadoLaboralAsync(PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest request) {
            return base.Channel.ObtenerCertificadoLaboralAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerCertificadoLaboralResponse1> ObtenerCertificadoLaboralAsync(PasswordChange.boomiTest.ObtenerCertificadoLaboral ObtenerCertificadoLaboral) {
            PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest inValue = new PasswordChange.boomiTest.ObtenerCertificadoLaboralRequest();
            inValue.Body = new PasswordChange.boomiTest.ObtenerCertificadoLaboralRequestBody();
            inValue.Body.ObtenerCertificadoLaboral = ObtenerCertificadoLaboral;
            return ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ObtenerCertificadoLaboralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordChange.boomiTest.ObtenerDatosResponse1 PasswordChange.boomiTest.WebServiceProviderPortType.ObtenerDatos(PasswordChange.boomiTest.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public PasswordChange.boomiTest.ObtenerDatosResponse ObtenerDatos(PasswordChange.boomiTest.ObtenerDatos ObtenerDatos1) {
            PasswordChange.boomiTest.ObtenerDatosRequest inValue = new PasswordChange.boomiTest.ObtenerDatosRequest();
            inValue.Body = new PasswordChange.boomiTest.ObtenerDatosRequestBody();
            inValue.Body.ObtenerDatos = ObtenerDatos1;
            PasswordChange.boomiTest.ObtenerDatosResponse1 retVal = ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerDatosResponse1> PasswordChange.boomiTest.WebServiceProviderPortType.ObtenerDatosAsync(PasswordChange.boomiTest.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordChange.boomiTest.ObtenerDatosResponse1> ObtenerDatosAsync(PasswordChange.boomiTest.ObtenerDatos ObtenerDatos) {
            PasswordChange.boomiTest.ObtenerDatosRequest inValue = new PasswordChange.boomiTest.ObtenerDatosRequest();
            inValue.Body = new PasswordChange.boomiTest.ObtenerDatosRequestBody();
            inValue.Body.ObtenerDatos = ObtenerDatos;
            return ((PasswordChange.boomiTest.WebServiceProviderPortType)(this)).ObtenerDatosAsync(inValue);
        }
    }
}
